// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_streber = "CgkIoNu8374PEAIQEA"; // <GPGSID>
        public const string achievement_nicht_jetzt = "CgkIoNu8374PEAIQCA"; // <GPGSID>
        public const string achievement_willkommen_in_partikel_rush = "CgkIoNu8374PEAIQAQ"; // <GPGSID>
        public const string achievement_stressig = "CgkIoNu8374PEAIQDA"; // <GPGSID>
        public const string leaderboard_highscore = "CgkIoNu8374PEAIQAg"; // <GPGSID>
        public const string achievement_ist_das_berhaupt_mglich = "CgkIoNu8374PEAIQDQ"; // <GPGSID>
        public const string achievement_shoppingqueen = "CgkIoNu8374PEAIQCQ"; // <GPGSID>
        public const string achievement_nochmal = "CgkIoNu8374PEAIQDg"; // <GPGSID>
        public const string achievement_guter_score = "CgkIoNu8374PEAIQCw"; // <GPGSID>
        public const string achievement_hallo_welt = "CgkIoNu8374PEAIQBw"; // <GPGSID>
        public const string achievement_ehre = "CgkIoNu8374PEAIQEQ"; // <GPGSID>
        public const string achievement_level_up = "CgkIoNu8374PEAIQCg"; // <GPGSID>
        public const string achievement_9000 = "CgkIoNu8374PEAIQDw"; // <GPGSID>

}

